---

- name: Download adore-djatoka
  sudo: yes
  get_url:
    url: http://downloads.sourceforge.net/project/djatoka/djatoka/{{ djatoka.version }}/adore-djatoka-{{ djatoka.version }}.tar.gz
    dest: "{{ djatoka.install_path }}-{{ djatoka.version }}.tar.gz"

- name: untar adore-djatoka
  sudo: yes
  unarchive:
    src: "{{ djatoka.install_path }}-{{ djatoka.version }}.tar.gz"
    dest: "{{ djatoka.parent_dir }}"
    copy: no

- name: Change ownership to tomcat and update permissions
  sudo: yes
  file:
    path: "{{ djatoka.install_path }}-{{ djatoka.version }}"
    owner: tomcat7
    recurse: yes

- name: Symlink adore-djatoka with version
  sudo: yes
  file:
    path: "{{ djatoka.install_path }}"
    src: /opt/adore-djatoka-1.1
    state: link

- name: Add KDU library on load.
  sudo: yes
  copy:
    src: kdu_libs.conf
    dest: /etc/ld.so.conf.d/kdu_libs.conf
    mode: 0644

- name: Run LDConfig
  sudo: yes
  command: ldconfig

- name: Create link to Kakadu compress
  sudo: yes
  file:
    src: "{{ djatoka.install_path }}/bin/Linux-x86-64/kdu_compress"
    dest: /usr/local/bin/kdu_compress
    state: link

- name: Create link to Kakadu expand
  sudo: yes
  file:
    src: "{{ djatoka.install_path }}/bin/Linux-x86-64/kdu_expand"
    dest: /usr/local/bin/kdu_expand
    state: link

- name: Create link to djatoka inside Tomcat
  sudo: yes
  file:
    src: "{{ djatoka.install_path }}/dist/adore-djatoka.war"
    dest: "{{ tomcat.install_path }}/webapps/adore-djatoka.war"
    state: link

- name: Replace tomcat7 defaults - change to /etc/default/tomcat7 once sorted
  sudo: yes
  copy:
    src: tomcat7.conf
    dest: /root/tomcat7
    mode: 0644

- name: Restart tomcat7
  sudo: yes
  service:
    name: tomcat7
    state: restarted

- name: Wait 30 seconds
  pause:
    seconds: 30

- name: Replace djatoka logging defaults
  sudo: yes
  copy:
    src: log4j.properties
    dest: "{{ tomcat.install_path }}/webapps/adore-djatoka/WEB-INF/classes/log4j.properties"
    mode: 0644

- name: Restart tomcat7
  sudo: yes
  service:
    name: tomcat7
    state: restarted
