---

- name: Update apt
  sudo: yes
  apt:
    update_cache: yes

- name: Install system packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties
    - mcrypt
    - git
    - sendmail
    - zip
    - unzip
    - openjdk-7-jdk
    - maven

- name: Update apt again
  sudo: yes
  apt:
    update_cache: yes
