---
- hosts: all
  sudo:  yes
  vars:
    server_ip: localhost
    doc_root: /var/www/web
    tomcat:
      install_path: /var/lib/tomcat7
      source_path: /usr/share/tomcat7
    java_packages:
      - oracle-java7-set-default
      - oracle-java7-installer
      - openjdk-7-jdk
  roles:
    - init
    - tomcat7
    - apache2
    - mysql
    - solr
    - fedora-commons
    - fedoragsearch
    - php5
    - drupal-drush
    - imagemagick
    - exiftool
    - tesseract-ocr
    - freelib-djatoka
