---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
  roles:
    - init
    - imagemagick
    - exiftool
    - tesseract-ocr
    - mysql
    - tomcat7
    - apache2
    - adore-djatoka
    - php5
    - drupal-drush
