---
- hosts: all
  sudo:  yes
  vars:
    server_ip: localhost
    doc_root: /var/www/web
    tomcat:
      install_path: /var/lib/tomcat7
  roles:
    - init
#    - apache2
    - tomcat7
    - mysql
    - fedora-commons
#    - solr
#    - php5
#    - drupal-drush
#    - imagemagick
#    - exiftool
#    - tesseract-ocr
#    - freelib-djatoka
#    - adore-djatoka
