---
  # Only use with solr versions > 4.2.0

- name: Download Solr
  sudo: yes
  command: wget -O {{ solr.install_path }}-{{ solr.version }}.tgz http://archive.apache.org/dist/lucene/solr/{{ solr.version }}/solr-{{ solr.version }}.tgz
  args:
    creates: "{{ solr.install_path}}-{{ solr.version }}.tgz"

- name: Untar Solr
  sudo: yes
  unarchive:
    src: "{{ solr.install_path }}-{{ solr.version }}.tgz"
    dest: "{{ solr.parent_dir }}"
    copy: no
    creates: "{{ solr.install_path }}-{{ solr.version }}/CHANGES.txt"

- name: Change ownership to www-data and update permissions
  sudo: yes
  file:
    path: "{{ solr.install_path }}-{{ solr.version }}"
    owner: tomcat7
    recurse: yes

- name: Symlink Solr to proper install path
  sudo: yes
  file:
    src: "{{ solr.install_path }}-{{ solr.version }}"
    path: "{{ solr.install_path }}"
    state: link

- name: Copy example configuration
  sudo: yes
  sudo_user: tomcat7
  command: cp -R {{ solr.install_path }}/example/solr/collection1 {{ solr.install_path }}/{{ solr.core_name }}
  args:
    creates: "{{ solr.install_path }}/{{ solr.core_name }}"

- name: Add Tomcat-Solr XML
  sudo: yes
  sudo_user: tomcat7
  template:
    src: tomcat_solr.xml.j2
    dest: "{{ tomcat.home }}/conf/Catalina/localhost/solr.xml"

- name: Add Solr Core XML
  sudo: yes
  sudo_user: tomcat7
  template:
    src: solr.xml.j2
    dest: "{{ solr.install_path }}/solr.xml"

- name: Symlink Solr inside Tomcat
  sudo: yes
  sudo_user: tomcat7
  file:
    src: "{{ solr.install_path }}/dist/solr-{{ solr.version }}.war"
    dest: "{{ tomcat.home }}/webapps/solr.war"
    state: link

- name: Restart tomcat7
  sudo: yes
  service:
    name: tomcat7
    state: restarted

- name: Wait 30 seconds
  pause:
    seconds: 30

- name: Create ext directory if it does not already exist
  sudo: yes
  sudo_user: tomcat7
  file:
    path: "{{ solr.install_path }}/example/lib/ext"
    state: directory

- name: Copy necessary libraries
  sudo: yes
  shell: "cp -R {{ solr.install_path }}/example/lib/ext/*.jar {{ tomcat.home }}/webapps/solr/WEB-INF/lib"
  notify: restart tomcat7
