---

- name: Download Fedora Commons
  sudo: yes
  command: wget -O /opt/fedora.jar http://downloads.sourceforge.net/project/fedora-commons/fedora/{{ fedora.version }}/fcrepo-installer-{{ fedora.version }}.jar

- name: Copy install properties
  sudo: yes
  template:
    src: install.properties.j2
    dest: /opt/install.properties

- name: Install fedora commons
  sudo: yes
  command: java -jar fedora.jar install.properties
  args:
    chdir: /opt

- name: Change ownership to Tomcat and update permissions
  sudo: yes
  file:
    path: "{{ fedora.install_path }}"
    owner: tomcat7
    group: tomcat7
    mode: g+rwx
    recurse: yes
